gomonitor:
   build: .
   ports:
    - "8080:8080"
   links:
    - mongo
    - elastic
   volumes:
    - ./config:/config
elastic:
   image: docker.io/elasticsearch:2.2
   volumes:
    - ./data/elastic:/usr/share/elasticsearch/data
   ports:
    - "9200:9200"
    - "9300:9300"
redis:
   image: docker.io/redis
   volumes:
    - ./data/redis:/data
   ports:
    - "6379:6379"
mongo:
   image: docker.io/mongo
   volumes:
    - ./data/mongo:/data/db
   ports:
    - "27017:27017"
shipper:
  build: ./config/shipper
  volumes:
    - ./config/shipper:/config-dir 
  links:
    - redis
    - elastic
kibana:
   image: docker.io/kibana:4.4
   links:
    - elastic:elasticsearch
   ports:
    - "5601:5601"
